//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCBankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Created_Date { get; set; }
        public long CustomerID { get; set; }
        public System.Guid TransactionRef { get; set; }
        public string State { get; set; }
    
        public virtual Customer_Detail Customer_Detail { get; set; }
    }
}
